"""Shared internal constants for Doom rule semantics."""

START_MODE_IMMEDIATE = "immediate"
START_MODE_DEFERRED = "deferred"
START_MODE_MENU = "menu"
START_MODE_VALUES = [
    START_MODE_IMMEDIATE,
    START_MODE_DEFERRED,
    START_MODE_MENU,
]

START_MAP_STYLE_WARP = "warp"
START_MAP_STYLE_MAP = "map"
START_MAP_STYLE_VALUES = [
    START_MAP_STYLE_WARP,
    START_MAP_STYLE_MAP,
]

MAP_NAMESPACE_STYLE_UNKNOWN = "unknown"
MAP_NAMESPACE_STYLE_EPISODE = "episode"
MAP_NAMESPACE_STYLE_MAPXX = "mapxx"
MAP_NAMESPACE_STYLE_VALUES = [
    MAP_NAMESPACE_STYLE_UNKNOWN,
    MAP_NAMESPACE_STYLE_EPISODE,
    MAP_NAMESPACE_STYLE_MAPXX,
]
